name: Init Variables CI
on:
  push:    
  pull_request:
    branches: [ master, develop ]

jobs:
  Init:
    runs-on: ubuntu-latest
    name: Init Variables
    steps:
      - name: Variables
        env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
            ENV_CONTEXT: ${{ toJson(env) }}
            JOB_CONTEXT: ${{ toJson(job) }}
            STEPS_CONTEXT: ${{ toJson(steps) }}
            RUNNER_CONTEXT: ${{ toJson(runner) }}
            SECRETS_CONTEXT: ${{ toJson(secrets) }}
            STRATEGY_CONTEXT: ${{ toJson(strategy) }}
            MATRIX_CONTEXT: ${{ toJson(matrix) }}
            NEEDSCONTEXT: ${{ toJson(needs) }}
        run: |
          echo "GITHUB_CONTEXT: $GITHUB_CONTEXT"
          echo "ENV_CONTEXT: $ENV_CONTEXT"
          echo "JOB_CONTEXT: $JOB_CONTEXT"
          echo "STEPS_CONTEXT: $STEPS_CONTEXT"
          echo "RUNNER_CONTEXT: $RUNNER_CONTEXT"
          echo "SECRETS_CONTEXT: $SECRETS_CONTEXT"
          echo "STRATEGY_CONTEXT: $STRATEGY_CONTEXT"
          echo "MATRIX_CONTEXT: $MATRIX_CONTEXT"
          echo "NEEDSCONTEXT: $NEEDSCONTEXT"